### ISSUE TITLE
browser_click not clicking

### ISSUE THREAD

**Issue by blex2011** [autobrowser-ai/mcp#75]
I see the arrow appear in the correct place on the page but it never clicks. I have tried on many pages. I'm using latest version and chrome extension on Mac... 

Here is an example

![Image](https://github.com/user-attachments/assets/cdc73ff3-ea98-46e3-858b-16fad578f818)

Here is the results in cursor:

- Page URL: https://github.com/BrowserMCP/mcp/issues/new
- Page Title: New Issue
- Page Snapshot
```yaml
- document [ref=s2e2]:
  - link "Skip to content" [ref=s2e6]:
    - /url: "#start-of-content"
  - banner [ref=s2e11]:
    - heading "Navigation Menu" [level=2] [ref=s2e12]
    - button "Open global navigation menu" [ref=s2e19]
    - link "Homepage" [ref=s2e21]:
      - /url: https://github.com/
    - navigation "GitHub Breadcrumb" [ref=s2e24]:
      - list [ref=s2e25]:
        - listitem [ref=s2e26]:
          - link "BrowserMCP" [ref=s2e27]:
            - /url: /BrowserMCP
          - text: /
        - listitem [ref=s2e32]:
          - link "mcp" [ref=s2e33]:
            - /url: /BrowserMCP/mcp
    - button "Type / to search" [ref=s2e43]
    - link "Chat with Copilot" [ref=s2e53]:
      - /url: /copilot
    - button "Open Copilot…" [ref=s2e59]
    - button "Create something new" [ref=s2e64]
    - link "Your issues" [ref=s2e70]:
      - /url: /issues
    - link "Your pull requests" [ref=s2e71]:
      - /url: /pulls
    - link "You have no unread notifications" [ref=s2e73]:
      - /url: /notifications
    - button "Open user navigation menu" [ref=s2e79]
    - navigation "Repository" [ref=s2e88]:
      - list [ref=s2e89]:
        - listitem [ref=s2e90]:
          - link "Code" [ref=s2e91]:
            - /url: /BrowserMCP/mcp
        - listitem [ref=s2e93]:
          - link "Issues 42" [ref=s2e94]:
            - /url: /BrowserMCP/mcp/issues
        - listitem [ref=s2e97]:
          - link "Pull requests 2" [ref=s2e98]:
            - /url: /BrowserMCP/mcp/pulls
        - listitem [ref=s2e101]:
          - link "Actions" [ref=s2e102]:
            - /url: /BrowserMCP/mcp/actions
        - listitem [ref=s2e104]:
          - link "Projects" [ref=s2e105]:
            - /url: /BrowserMCP/mcp/projects
        - listitem [ref=s2e107]:
          - link "Security" [ref=s2e108]:
            - /url: /BrowserMCP/mcp/security
        - listitem [ref=s2e110]:
          - link "Insights" [ref=s2e111]:
            - /url: /BrowserMCP/mcp/pulse
  - main [ref=s2e117]:
    - region [ref=s2e120]
    - link "View blex2011's profile" [ref=s2e126]:
      - /url: /blex2011
      - text: View blex2011's profile
      - img [ref=s2e128]
    - heading "Create new issue" [level=2] [ref=s2e131]
    - text: Add a title *
    - textbox "Add a title" [ref=s2e145]: browser_click not clicking
    - group "Add a description" [ref=s2e150]:
      - text: "Add a description Markdown input: edit mode selected."
      - navigation "View mode" [ref=s2e159]:
        - tablist [ref=s2e160]:
          - tab "Write" [selected] [ref=s2e161]
          - tab "Preview" [ref=s2e162]
      - toolbar "Formatting tools" [ref=s2e164]:
        - button "Heading" [ref=s2e166]
        - button "Bold" [ref=s2e167]
        - button "Italic" [ref=s2e168]
        - button "Quote" [ref=s2e171]
        - button "Code" [ref=s2e172]
        - button "Link" [ref=s2e173]
        - button "Unordered list" [ref=s2e176]
        - button "Numbered list" [ref=s2e177]
        - button "Task list" [ref=s2e178]
        - button "Mention" [ref=s2e181]
        - button "Reference" [ref=s2e182]
        - button "Saved replies" [ref=s2e183]
        - button "Slash commands" [ref=s2e184]
      - textbox "Markdown value" [ref=s2e187]: I see the arrow appear in the correct place on the page but it never clicks. Here is an example
      - alert [ref=s2e188]
      - button "Paste, drop, or click to add files" [ref=s2e192]
    - heading "Metadata" [level=2] [ref=s2e200]
    - heading "Assignees" [level=3] [ref=s2e204]
    - text: No one assigned
    - heading "Labels" [level=3] [ref=s2e209]
    - text: No labels
    - heading "Type" [level=3] [ref=s2e214]
    - text: No type
    - heading "Projects" [level=3] [ref=s2e219]
    - text: No projects
    - heading "Milestone" [level=3] [ref=s2e224]
    - text: No milestone
    - checkbox "Create more" [ref=s2e232]
    - text: Create more
    - status [ref=s2e235]
    - button "Cancel" [ref=s2e237]
    - button "Create ( command enter )" [ref=s2e240]
  - contentinfo [ref=s2e250]:
    - heading "Footer" [level=2] [ref=s2e251]
    - link "GitHub Homepage" [ref=s2e254]:
      - /url: https://github.com
    - text: © 2025 GitHub, Inc.
    - navigation "Footer" [ref=s2e256]:
      - heading "Footer navigation" [level=3] [ref=s2e257]
      - list "Footer navigation" [ref=s2e258]:
        - listitem [ref=s2e259]:
          - link "Terms" [ref=s2e260]:
            - /url: https://docs.github.com/site-policy/github-terms/github-terms-of-service
        - listitem [ref=s2e261]:
          - link "Privacy" [ref=s2e262]:
            - /url: https://docs.github.com/site-policy/privacy-policies/github-privacy-statement
        - listitem [ref=s2e263]:
          - link "Security" [ref=s2e264]:
            - /url: https://github.com/security
        - listitem [ref=s2e265]:
          - link "Status" [ref=s2e266]:
            - /url: https://www.githubstatus.com/
        - listitem [ref=s2e267]:
          - link "Docs" [ref=s2e268]:
            - /url: https://docs.github.com/
        - listitem [ref=s2e269]:
          - link "Contact" [ref=s2e270]:
            - /url: https://support.github.com?tags=dotcom-footer
        - listitem [ref=s2e271]:
          - button "Manage cookies" [ref=s2e273]
        - listitem [ref=s2e274]:
          - button "Do not share my personal information" [ref=s2e276]
  - text: New Issue 3 results
  - document [ref=s2e281]:
    - img [ref=s2e286]
```

![Image](https://github.com/user-attachments/assets/89b16aa0-3bb7-4c15-b36b-8f6856ae5a9b)
